import = ["~/.config/alacritty/themes/tokyo-night.toml"]

[font]
size = 8.0

[font.normal]
family = "Source Code Pro"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
